### PR TITLE
BUG: Update name of plot class

### LINKED ISSUE #10: Update PlotData to PlotSeries
Following changes in https://github.com/Slicer/Slicer/commit/082edc40c

PlotData was renamed to PlotSeries

### PR DESCRIPTION
**Pull request by phcerdan**
Renamed PlotData to PlotSeries

More info:
https://www.slicer.org/wiki/Documentation/Nightly/Developers/Tutorials/MigrationGuide/Slicer

Closes #10

### CODE REVIEW

**Comment by phcerdan** [comment]
This requires update to Slicer 4.9

**Comment by jamesfishbaugh** [comment]
@phcerdan will this work if I am building against the current version of SlicerSALT?

**Comment by phcerdan** [comment]
Yes, SlicerSALT is using right now a [modern slicer version](https://github.com/Slicer/Slicer/commit/c88b17d38acf99c66892f867aff163a9c07d073a)

**Comment by jamesfishbaugh** [comment]
I get an error when trying to create the plot:

```
Traceback (most recent call last):
  File "/storage/projects/SlicerSALT/ShapeRegressionExtension_git/build/ShapeRegressionExtension-build/lib/Slicer-4.8/qt-scripted-modules/RegressionVisualization.py", line 817, in onRegressionPlot
    plotChartNode.RemoveAllPlotSeriesNodeIDs()
AttributeError: 'vtkCommonCorePython.vtkMRMLPlotChartNode' object has no attribute 'RemoveAllPlotSeriesNodeIDs'
```

**Comment by phcerdan** [comment]
You are using Slicer-4.8, I can see from your error message: `build/ShapeRegressionExtension-build/lib/Slicer-4.8/`

Maybe you are providing a `-DSlicer_DIR:PATH=/path/Slicer-build/Slicer-build` different than the one you used in SlicerSALT.

If you want to use the SlicerSALT one use something like: (names may change depending on your convention except for the last `Slicer-build`)
`-DSlicer_DIR:PATH=/path/SlicerSALT-build/Slicer-build`

**Comment by phcerdan** [comment]
Merge https://github.com/KitwareMedical/ShapeRegressionExtension/pull/12, and you will get a configuration error if you try to build with an older slicer.

**Pull request merged**
