### PR TITLE
WIP:BUG: Fix Regression Visualization IO

### PR DESCRIPTION
**Pull request by phcerdan**
Drop usage of MRMLUtility in Regression Visualization in favour
of slicer.util functions.

### CODE REVIEW

**Comment by phcerdan** [comment]
Fix #7

**Comment by jamesfishbaugh** [comment]
@phcredan I now get an error when generating the volume plot.

```
Traceback (most recent call last):
  File "/storage/projects/SlicerSALT/ShapeRegressionExtension_git/build/ShapeRegressionExtension-build/lib/Slicer-4.8/qt-scripted-modules/RegressionVisualization.py", line 861, in onRegressionPlot
    success, model = slicer.mrmlScene.loadModel(self.shapePaths[i], returnNode=True)
AttributeError: 'vtkCommonCorePython.vtkMRMLScene' object has no attribute 'loadModel'
```

**Comment by phcerdan** [comment]
Good catch, change `mrmlScene` for `util` there.

Sorry I haven't tested the plot yet (the PR was WIP), but it should be ok, I will send another PR fixing this.

**Comment by phcerdan** [comment]
Fixed in #9, please merge.

I am facing that the sequencemodel is not getting deleted... working on this.

**Pull request merged**
